//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DbMigs.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class db_migration_history
    {
        public int installed_rank { get; set; }
        public string version { get; set; }
        public string script { get; set; }
        public string installed_by { get; set; }
        public System.DateTime installed_on { get; set; }
        public bool success { get; set; }
        public string Error { get; set; }
        public Nullable<int> ExecutionId { get; set; }
    }
}
